### ISSUE TITLE
Still supporting it?

### ISSUE THREAD

**Issue by Tyuyf** [dafow/ytpl#1] opened 2020-03-06 23:16 UTC
I haven't been able to update my playlist through the site for about a year now. Tried adding a few of my playlists and a few random ones,  and I always get the error "An error occurred while synchronizing your playlist (make sure it's public". Just wondering if you're still supporting the website.

**Comment by dafow** [comment] 2020-03-08 18:09
Thanks for opening an issue. Due to the nature of the site, I don't really use it myself that much so I didn't notice this. I can reproduce the issue too and yes, I'm still supporting it for the moment (even plan to rework it completely), so I'll be working on a fix.

**Comment by dafow** [comment] 2020-04-14 04:29
@Tyuyf Wow that took longer than expected, but I had some free time with this coronavirus!
Should be fixed now, the Google API is really wonky and I had to re-generate a key. Let me know how it goes.
Also changed the playlist view to list 25 items instead of 5 since it made navigation a nightmare. Again, looking at the code 3 years later it's pretty horrible so I'll start working on a new version and of course migrate the old data.

**Comment by Tyuyf** [comment] 2020-04-14 18:13
Works beautifully! Definitely digging 25 instead of 5 items. Thank you so much for looking at it again; this is truly a one-of-a-kind website. I actually made a dark theme for the website for Stylus and Stylish, if you're interested. Might become obsolete once your new version comes out, though.
![aaa](https://user-images.githubusercontent.com/39038638/79258384-0c31c980-7e59-11ea-9863-d45e587eca04.png)
![aab](https://user-images.githubusercontent.com/39038638/79258409-10f67d80-7e59-11ea-9a6c-81efade7293e.png)

Here's the code for the dark theme: 
``` 
body {
    color: #CCC !important;
    background: #101010 !important; }

.navbar-default, .videos .video, .well {
    border-color: #050505 !important;
    background-color: #202020 !important; }

.list-group a {
    border-color: #050505 !important;
    background-color: #202020 !important; }
.list-group a:hover {
    background-color: #505050 !important; }

.title-history-form {
    border: 1px solid #050505 !important;
    background: #303030 !important; }

.form-control {
    box-shadow: none !important;
    border-color: #050505 !important;
    color: white !important;
    background: #505050 !important; }

.videos .video .btn-danger {
    color: white !important;
    border-color: #d43f3a !important;
    background-color: #d9534f !important; }
.videos .video .btn-danger:hover {
    border-color: #ac2925 !important;
    background-color: #c9302c !important; }

.content a {
    text-decoration: underline !important;
    color: #58ACFA !important; }
a {
    color: #CCC !important; }
a:hover {
    color: white !important; }

.btn, .pager li a {
    border-color: #050505 !important;
    color: #CCC !important;
    background: #303030 !important; }
.btn:hover, .pager li a:hover {
    color: white !important;
    background: #505050 !important; }
```

**Comment by dafow** [comment] 2020-04-22 03:06
Thanks for your input, will use it if I got some time!
And thanks for using the website :)

**Closed as completed by dafow** 2020-04-22 03:06 UTC
